config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#home'
get 'learn_html', to: "welcome#learn_html"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController#W and C have to be capitalize
  def home
  end

  def learn_html
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-languagge" content="vi", charset="UTF-8"> <!--write vietnamese in sublime text : push F2; so vn ime: on in the status, and preference setting in telex --> 
  <link rel="stylesheet" href="styles.css"
</head>
<body style="background-color:rgb(147, 186, 185);">

<h1> My applications are here </h1>
<p>This is an individual project, which the objectif is to code at leat 2 hours per day. Each project I do have to have a meaning. 
</p>
<p>
  <a href="#projects"> Here </a> the list of all my projects 
  <a href = "#todo"> Here </a> the list of all tasks todo update today
</p>

<p>The first project is to track the progress of all my projects. Begin the April 6th 2018. Deadline: April 6th 2018
</p>
<p> My favorite quote is <q>The history belongs to the one who have a dream</q> in a book of Daewoo's president Kim Woo Choong "It's a Big World and There's Lots to be Done". Below this content in vietnamese - my mother tongue
<blockquote>Lịch sử thuộc về những người biết ưóc mơ: Ước mơ là động lực làm thay dổi thế giới. Những người có ước mơ, những xã hội làm cho ước mơ trở thành hiện thực và đất nước biết chia sẻ ước mơ và tất cả mọi người có thể trở thành bậc anh hùng trong lịch sử thế giới. Tôi cam đoan rằng tất cả những người đang làm nên lịch sử thế giới ngày hôm nay đều có những ước mơ lớn khi còn trẻ
</blockquote> 
You can read this book in vietnamese <a href="https://fevent.files.wordpress.com/2011/03/tgronglonva-coquanhieuviecfailam-kimwoochung.pdf" target="_blank"> here </a>
</p>
<table style="width:100%; text-align: center;" id = "projects">
  <caption> Hong's projects list </caption>
  <tr>
    <th> Project names</th>
    <th> Begin </th>
    <th> Ending </th>
    <th> Progress </th>
    <th> Comments </th>
  </tr>
  <tr>
    <td> Tracking projects </td>
    <td> 06/04/18</td>
    <td> 07/04/18</td>
    <td> Late </td>
    <td> in progress </td> 
  <tr>
    <td> Datamining project </td>
    <td> 06/04/18 </td>
    <td> 06/06/18 </td>
    <td> first week : data preparation </td>
</table>  
<hr>
<h2> Todo Today </h2>
<table style="width: 100%; text-align: center;" id="todo">
  <caption> Hong's list todo today </caption>
  <tr> 
    <th> Date</th>
    <th> Todo </th>
    <th> Comments </th>
  </tr> 
  <tr>
    <td> 07/04/18 </td>
    <td> 
      <ul>
        <li> Slack list articles </li>
        <li> Feature engineering theory preparation </li>
        <li> Clothes preparation </li>
      </ul>
    </td>
  </tr>
</table>
<h2> Link to my projects</h2>

<%= link_to image_tag('algoski.png'), 'www.algo.ski' %>
<%= link_to 'Html', learn_html_path %>


</body>

</html>

app/views/welcome/learn_html.html.erb
<!DOCTYPE html>
<html lang = "en-US">
<head>
  <link rel="stylesheet" href="styles.css">
</head>
<body style="background-color: powderblue;">

<ul>
HTML Documents

<li> HTML Basic</li>
<li> HTML Elements</li>
<li> HTML Attributes</li>
<li> HTML Headings </li>
<li> HTML Paragraphs </li>
<li> HTML Styes</li>
<li> HTML Formatting</li>
<li> HTML Quotations</li>
<li> HTML Comments</li>
<li> HTML Colors</li>
<li> HTML CSS</li>
<li> HTML Links</li>
<li> HTML Images</li>
<li> HTML Tables </li>
<li> HTML Lists</li>
<li> HTML Blocks</li>
<li> HTML Classes</li>
<li> HTMl Id </li>
<li> HTML Iframes </li>
</ul>

<p>
All HTML documents must start with a document type declaration: <!DOCTYPE html>.
<br><br/>
The HTML document itself begins with <html> and ends with </html>.
<br><br/>
The visible part of the HTML document is between <body> and </body>. 
<br><br/>
<h1></h1>, <h2> </h2>, <h3> </h3> are headings
</p>
<hr>
<p>HTML links are defined with the <a> </a>
<br><br/>
The link's destination is specified in the href attribute. 
Ex: He're a link of my project : <a href="http://algo.ski/"> algo.ski </a>
</p>
<hr>
<p title = "images">
<h2 id = "images">HTML Images</h2>
<br><br/>
HTML images are defined with the <img> tag.
<br><br/>
The source file (src), alternative text (alt), width, and height are provided as attributes:
 <img src="w3schools.jpg" alt="W3Schools.com" width="104" height="142"> 
</p>
<hr>
<p title = "HTML_Button">
<h2>HTML Buttons</h2>
<br><br/>
HTML buttons are defined with the <button> tag:</button>
 <button>Click me</button> 
</p>
<hr>
<p title = "break">
<h2> Break </h2>
HTML elements with no content are called empty elements. Empty elements do not have an end tag, such as the <br> element (which indicates a line break).
</p>
<hr>
<p title="HTML_attribute">
<h2>HTML Attributes</h2>
<ul name = "HTML_Attribute">
All HTML elements can have attributes
<li>Attributes provide additional information about an element</li>
<li>Attributes are always specified in the start tag</li>
<li>Attributes usually come in name/value pairs like: name="value"</li>
</ul>
The href attribute specified the link adress. The src attribute specified the filename of the source, it goes with the image tag. The width and heitght attributes specify the size of the image and the alt attribute specifies an alternative text to be used when the photo can not be displayed. The style attribute is used to specify the styling of an element, like color, font, size,.... The lang attribute specifies the language of the html document. The title attribute is added to the paragraph element . 
Below is a list of some attributes often used in html: alt, disabled, href, id, src, style, title
</p>
<hr>
<p title= "headings" style="font-size: 35px;" >
<h2 style="font-size:50px;"> Headings </h2>
the <hr> tag defines a themactic break in an html pages, which is most often used as a horizontal rule.
</p>
<hr>
<p title = "styles" style="color:red; font-size: 35px;" >
<h2 style = "font-size: 50px"> HTML Styles </h2>
The HTML Style Attribute : Setting the style of an HTML element, can be done with the style attribute.

The HTML style attribute has the following syntax: <tagname style="property:value;">
<br>
The background-color property defines the background color for an HTML element.
<br>
This example sets the background color for a page to powderblue:  
<br>
<ul>
<li>Use the style attribute for styling HTML elements</li>
<li>Use background-color for background color</li>
<li>Use color for text colors</li>
<li>Use font-family for text fonts</li>
<li>Use font-size for text sizes</li>
<li>Use text-align for text alignment</li>
</ul>
</p>
<hr>

<p title = "formatting">
<h2> HTML Formatting</h2>
HTML also defines special elements for defining text with a special meaning.
<br><br/>
HTML uses elements like <b> and <i> for formatting output, like bold or italic text.
<br><br/>
Formatting elements were designed to display special types of text:

    <b> - Bold text</b>
    <strong> - Important text</strong>
    <i> - Italic text</i>
    <em> - Emphasized text</em>
    <mark> - Marked text</mark>
    <small> - Small text</small>
    <del> - Deleted text</del>
    <ins> - Inserted text</ins>
    <sub> - Subscript text</sub>
    <sup> - Superscript text</sup>
<br><br/>
For example, the distribution X<sup>2</sup> is a statistics <i>distribution</i>.
</p>
<hr>

<p title = "quotation" id="quotes01">
  <h2> Quotations </h2>
  HTML Quotation and Citation Elements
Tag   Description
abbr  Defines an abbreviation or acronym
address   Defines contact information for the author/owner of a document
bdo   Defines the text direction
blockquote  Defines a section that is quoted from another source
cite  Defines the title of a work
q   Defines a short inline quotation
</p>
<p title="css">
<h2> CSS</h2>
Use the HTML style attribute for inline styling
Use the HTML <style> element to define internal CSS
Use the HTML <link> element to refer to an external CSS file
Use the HTML <head> element to store </style> and <link> elements
Use the CSS color property for text colors
Use the CSS font-family property for text fonts
Use the CSS font-size property for text sizes
Use the CSS border property for borders
Use the CSS padding property for space inside the border
Use the CSS margin property for space outside the border
</p>
<hr>
<p title ="link">
<h2> HTML Link </h2>
The target attribute can have one of the following values:
<ul>
<li>_blank - Opens the linked document in a new window or tab</li>
<li>_self - Opens the linked document in the same window/tab as it was clicked (this is default)</li>
<li>_parent - Opens the linked document in the parent frame</li>
<li>_top - Opens the linked document in the full body of the window</li>
<li>framename - Opens the linked document in a named frame</li>
</ul>
It is common to use images as links
 <a href="default.asp">
  <img src="smiley.gif" alt="HTML tutorial" style="width:42px;height:42px;border:0;">
</a> 
border:0; is added to prevent IE9 (and earlier) from displaying a border around the image (when the image is a link).
You can review the html image part <a href="#images"> here </a>
In summary: 

Use the <a> element to define a link
Use the href attribute to define the link address
Use the target attribute to define where to open the linked document
Use the <img> element (inside <a>) to use an image as a link
Use the id attribute (id="value") to define bookmarks in a page
Use the href attribute (href="#value") to link to the bookmark
<br> <br/>
<%= link_to 'Home', root_path %>
</p>

</body>
</html>